### ISSUE TITLE
Having python 2.6 causes the package to not load

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/reticulate#77]
I am trying to make windows CI builds of a package that depends on reticulate on appveyor.
The image that appveyor uses to build R packages (via r-appveyor) has many python versions installed.
https://www.appveyor.com/docs/build-environment/#python. From 2.6 to latest 3.5

The trouble is reticulate is not compatible with 2.6 (2.6 doesn't have `sysconfig` module which came only in 2.7). Now the default path has python 2.7, but for some reason unknown to me , when doing `library(reticulate)`, python 2.6 is used for the initial stuff. I think is is even before `py_discover()` or `use_python()` comes in to play.  And so the package can't be loaded.

You can see https://github.com/krlmlr/r-appveyor/issues/91 for full error details. I am not even sure if having RETICULATE_PYTHON=<python 2.7+> will help in this case, as the path already have python 2.7 in it.

I think one thing reticulate can do is skip python < 2.7 as part of it's initial load even if it finds it.

**Comment by jjallaire** [comment]
`RETICULATE_PYTHON` should point to a Python binary or binary directory (perhaps it already does if python.exe is in C:\\Python53?). There are a couple of things which will cause reticulate to skip a version specified in RETICULATE_PYTHON:

1. If it's a different architecture (32bit vs. 64bit) than the R session.

2. If it doesn't have numpy installed

3. If it doesn't have the first Python module appearing in an `import` statement.

See: https://github.com/rstudio/reticulate/blob/master/R/config.R#L170

The issue is that with so many different versions of Python on a machine we need to do our very best to find the one that will work with the initial `import` statement.

All of that said though, I think that the problem here is that we error out when Python 2.6 is probed for configuration info. I think if I fix that and issue a warning instead that things may start working. Back with that fix soon.

**Comment by bhaskarvk** [comment]
Thanks for a quick response. It is my understanding too that the error occurs in the probing part, so the fix you suggested makes sense.

**Comment by jjallaire** [comment]
Should be addressed with this commit: https://github.com/rstudio/reticulate/commit/5532d40fa8b9825c57cf11b48b2faf55d99ad110

Can you try again and confirm the issue is resolved?

**Comment by bhaskarvk** [comment]
Unfortunately I don't have an easy way to test this out. The only windows env. I have access to is the CI build env. of appveyor, and for some reason there's is a temp directory with the reticulate package in it that's shadowing the reticulate package installed from GH. I have no idea where this temp directory comes from, and I don't think this has anything to do with reticulate package or the pthon 2.6 issue. So feel free to close this one out if your own tests work against a PY 2.6 install.

https://ci.appveyor.com/project/bhaskarvk/docker/build/1.0.19#L423

Or see below

```
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  [1] "C:/Users/appveyor/AppData/Local/Temp/1/RtmpucvD1N/RLIBS_e2c1c6a7322"
  [2] "C:/R/library"                                                       
  > library(testthat)
  > library(reticulate)
  > py_discover_config("docker")
  Traceback (most recent call last):
    File "C:/Users/appveyor/AppData/Local/Temp/1/RtmpucvD1N/RLIBS_e2c1c6a7322/reticulate/config/config.py", line 8, in <module>
      sys.stdout.write('\nVersionNumber: ' + str(sys.version_info.major) + '.' + str(sys.version_info.minor))
  AttributeError: 'tuple' object has no attribute 'major'
  Error in python_config(python_version, required_module, python_versions) : 
    Error 1 occurred running C:\Python26\\python.exe 
  Calls: py_discover_config -> python_config
  In addition: Warning message:
  running command '"C:\Python26\\python.exe" "C:/Users/appveyor/AppData/Local/Temp/1/RtmpucvD1N/RLIBS_e2c1c6a7322/reticulate/config/config.py"' had status 1 
  Execution halted
* DONE
Status: 1 ERROR

```

**Comment by bhaskarvk** [comment]
OK I managed to work around the .libPaths() issue by explicitly setting `c:/RLibrary' as the first entry, so now the GH version is picked up and it's still not working (but with a different issue this time).

```
  [2] "C:/Users/appveyor/AppData/Local/Temp/1/RtmpIJoEI6/RLIBS_f8470c6256f"
  [3] "C:/R/library"                                                       
  > library(testthat)
  > library(reticulate)
  > py_discover_config("docker")
  Traceback (most recent call last):
    File "C:/RLibrary/reticulate/config/config.py", line 8, in <module>
      sys.stdout.write('\nVersionNumber: ' + str(sys.version_info.major) + '.' + str(sys.version_info.minor))
  AttributeError: 'tuple' object has no attribute 'major'
  Error in python_config(python_version, required_module, python_versions) : 
    Error 1 occurred running C:\Python26\\python.exe 
  Calls: py_discover_config -> python_config
  In addition: Warning message:
  running command '"C:\Python26\\python.exe" "C:/RLibrary/reticulate/config/config.py"' had status 1 
  Execution halted
* DONE
Status: 1 ERROR
See
```

I think this is because sys.version_info got some changes in 2.7
From https://docs.python.org/2/library/sys.html#sys.version_info Changed in version 2.7: Added named component attributes. For 2.6 you probably need to access it via index. :)

Btw super thanks for such quick turn around time :+1:

**Comment by jjallaire** [comment]
I just changed to access by index. Could you try again? (I don't have a version of Python 2.6 to test with either so appreciate your help in verifying!)

**Comment by bhaskarvk** [comment]
Great, it now works with python2.6, or rather carefully sidesteps 2.6, which is what I wanted. My code needs some more fixing, but that's entirely on my side. Thanks again for a quick fix.

**Comment by jjallaire** [comment]
Great, thanks for the report and glad we got that sorted out!

**Comment by bhaskarvk** [comment]
Rather thank you for fixing it so quickly. If you get a chance take a look at my docker package (not on CRAN yet). With `reticulate` + `docker` I think it will open a window of opportunities for building all sorts of automated unit/integration testing envs, and not to mention automated reproducible research workflows.

Immediately I see `docker` very useful for automated testing of DB wrapping packages, where you can start a `docker` container for the DB, test the API and destroy the container, all from the R test script.
