### ISSUE TITLE
_import_hook failure when loading module via import_from_path

### ISSUE THREAD

**Issue by mmuurr** [rstudio/reticulate#917]
This is somewhat tricky, so I'll try to explain it as clearly as possible, and to help an example package that has this error is available [here](https://github.com/mmuurr/sqlparse-R-package) for testing.

The package linked-to above has a very small and simple structure:
```
R/zzz.R
inst/python/sqlparse/...
```
`inst/python/sqlparse` is a Python module (version-pinned to a few years back for compatibility with Python 2.x, since that's still the version distributed by default on most OSes).
`zzz.R` contains an `.onLoad()` hook that loads the aforementioned module via `import_from_path()` and then adds each top-level module object to the package namespace; effectively an automated way to 'mimic' the Python module's namespace.

[Here's that `.onLoad()` function](https://github.com/mmuurr/sqlparse-R-package/blob/master/R/zzz.R#L1):
```r
.onLoad <- function(libname, pkgname) {
    pkg_ns_env <- parent.env(environment())
    sqlparse <- reticulate::import_from_path("sqlparse", system.file("python", "sqlparse", package = pkgname, mustWork = TRUE))
    lapply(names(sqlparse), function(name) assign(name, sqlparse[[name]], pkg_ns_env))
}
```

In the current dev version of reticulate, when I try to build or load the R package, I receive the following error (preceded here by a successful `py_config()` call to help with debugging):
```r
reticulate::py_config()
# python:         /usr/bin/python
# libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
# pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
# version:        2.7.16 (default, Dec 13 2019, 18:00:32)  [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
# numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
# numpy_version:  1.8.0
#
# python versions found:
# /usr/bin/python3
# /usr/bin/python

library(sqlparse)
# Error: package or namespace load failed for ‘sqlparse’:
#  .onLoad failed in loadNamespace() for 'sqlparse', details:
#   call: py_get_attr_types_impl(x, names, resolve_properties)
#   error: AttributeError: type object 'module' has no attribute 'cli'
#
# Detailed traceback:
#   File "/usr/local/lib/R/4.0/site-library/reticulate/python/rpytools/loader.py", line 31, in _import_hook
#     level=level
```

I can verify this was working with reticulate 1.16 (and any version prior to that from early-2018 onward). The sqlparse Python module embedded in the package does have a `cli` sub-module, and so I suspect the `_import_hook` is choking on that somehow, but I'm kind of stumped as to what might be happening here.

**Comment by kevinushey** [comment]
Thanks for the report! I can reproduce as well:

```
> library(sqlparse)
Error: package or namespace load failed for 'sqlparse':
 .onLoad failed in loadNamespace() for 'sqlparse', details:
  call: py_get_attr_types_impl(x, names, resolve_properties)
  error: AttributeError: type object 'module' has no attribute 'cli'

Detailed traceback: 
  File "/Users/kevinushey/Library/R/4.0/library/reticulate/python/rpytools/loader.py", line 31, in _import_hook
    level=level
```

It seems like this only happens with Python 2 (not Python 3) so I'll have to see if I can figure out what's going on.

**Comment by LTLA** [comment]
FWIW I have a very similar problem, also with loading a Python 2 environment. Trawling the Git history, I tracked down the problematic change as 0c61662c9c8108f7c18148a7e67c41294da45c46, and setting `options(reticulate.useImportHook=FALSE)` restores functionality.

**Comment by kevinushey** [comment]
Thanks! I've disabled the load hook altogether for Python 2 with https://github.com/rstudio/reticulate/commit/a34d58f6d0561440b9860b66bae67cc49167161d.

We technically don't support Python 2.7 anymore, though (and neither does the Python Software Foundation) so if at all possible I'd recommend moving to Python 3.x.

**Comment by LTLA** [comment]
I couldn't agree more... Unfortunately, we got saddled with a bunch of legacy scripts, so it'll be nice to be able to coax them into working for just a bit longer. Hopefully, by the time they break for real, they won't be my problem any more 😃

**Comment by mmuurr** [comment]
@kevinushey thanks much for the speedy look at this, your work's much appreciated! Out of curiosity, what does the `_import_hook` provide to Python 3 that it doesn't for Python 2?

Re: not supporting Python 2 anymore; in spirit I completely agree, though in practice I think this is going to be painful. Obviously the Python Software Foundation declaring end-of-support for Python 2 is good reason to 'move on', but until most OS distributions stop including 2 as their default Python implementation (Mac OS X and basically all major Linux distros still!), I fear lots of potential breakages :-/

**Comment by kevinushey** [comment]
> Out of curiosity, what does the _import_hook provide to Python 3 that it doesn't for Python 2?

These hooks are primarily to be used by front-ends so that they can take some action if a Python module is loaded. RStudio uses this to inject hooks for e.g. `matplotlib`, so it can detect when a plot is created or shown (and re-route that to the Plots pane). Regular scripts outside of that context shouldn't need to worry, at least.

**Comment by kevinushey** [comment]
I believe the underlying issue here is now fixed -- thanks for reporting.
